### PR TITLE
fix: Kill microservice if a process signal is received

### LINKED ISSUE #252: 🐞 [Bug]: Executor doesn't kill all child processes
### Contact Details

gorez.tony@gmail.com

### What happened?

Sometimes the executor doesn't succeed in killing all child processes he creates.

## Improvement

Let's improve a few points that could avoid this situation:

- [ ] Don't use the `shell: true` option, counterpart: we have to parse the command and extract the command and args
- [ ] Add a `process.on('exit')` listener and kill the process when triggered.
- [ ] Don't use an npm script as a command, encourage people to use the command behind, ex: `node server.js` instead of `npm run dev` (if sub-processes are generated is the user's job to handle shutdown properly)

## Potential gain

**Before**: 3 processes spawn (shell + npm + the actual command)
**After**: 1 process (the actual command)

### Relevant log output

_No response_

### 🙏 Would you be willing to submit a PR?

Yes

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by olivierodo**
## Change description

> Let's try to fix a major stability issues. While RestQA get shutdown suddenly the child process remain orphan and blocking another run of RestQA.

## Type of change
- [X] Bug fix (fixes an issue)
- [ ] New feature (adds functionality)

## Related issues

Fix #252

### Development

- [x] Lint rules pass locally
- [x] Application changes have been tested thoroughly
- [x] Automated tests covering modified code pass

### Security

- [x] Security impact of change has been considered
- [x] Code follows project security practices and guidelines

### Code review 

- [x] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [x] Changes have been reviewed by at least one other contributor
- [x] Pull request linked to issue tracker where applicable

### CODE REVIEW

File: packages/core-microservice/src/index.js [hunk 1]
```diff
@@ -147,29 +156,31 @@ class Microservice {
...
+            }, 200);
           } else {
             isOut = true;
             reject(
               new Error(
                 format(
                   Locale().service.run.error_port_timeout,
                   port,
-                  DEFAULT_TIMEOUT
+                  this.timeout
```
Comment (tony-go) [inline packages/core-microservice/src/index.js:183]: Could you just double-check that in `this` context, this doesn't refer to something else? But maybe you decide to use a fat arrow instead of a function declaration.

File: packages/core-microservice/tests/index.test.js [hunk 2]
```diff
@@ -88,3 +122,266 @@ describe("#Microservice", () => {
...
+      port: 9090,
+      command: "node " + serverFilename,
+      silent: true,
+      timeout: 1000,
+      state: {
+        outputStream: {
+          addDebugLog
+        }
+      }
+    };
```
Comment (tony-go) [inline packages/core-microservice/tests/index.test.js:178]: I think we could abstract this into a helper function, as a lot of these properties don't change a lot.

```js
function buildMicroserviceOptions(fixtureName, overridedOptions) {
    const serverFilename = path.resolve(__dirname, "fixture", fixtureName");
    const addDebugLog = jest.fn();
    const options = {
      port: 9090,
      command: "node " + serverFilename,
      silent: true,
      timeout: 1000,
      state: {
        outputStream: {
          addDebugLog
        }
      },
      ...overridedOptions
    };

   return options
}
```

It's more an idea it could be done into another PR anyway

**Review by tony-go — APPROVED** [review]
